//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoltenMercury.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MoltenMercury.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AboutMC {
            get {
                return ResourceManager.GetString("AboutMC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AboutMCU {
            get {
                return ResourceManager.GetString("AboutMCU", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap arrow_down_30 {
            get {
                object obj = ResourceManager.GetObject("arrow_down_30", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow_up_30 {
            get {
                object obj = ResourceManager.GetObject("arrow_up_30", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chara_00001 {
            get {
                object obj = ResourceManager.GetObject("chara_00001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chara_00002 {
            get {
                object obj = ResourceManager.GetObject("chara_00002", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap diskette_30 {
            get {
                object obj = ResourceManager.GetObject("diskette_30", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///
        ///&lt;localization&gt;
        ///&lt;locale name=&quot;English&quot; code=&quot;en-us&quot;&gt;
        ///      
        ///      &lt;!-- Main Menu --&gt;
        ///      &lt;string key=&quot;MMS_FILE&quot;&gt;File&lt;/string&gt;
        ///      &lt;string key=&quot;MMS_SEL_CHAR&quot;&gt;Select Character&lt;/string&gt;
        ///      &lt;string key=&quot;MMS_LOAD_CHAR_RES&quot;&gt;Load Character Resources&lt;/string&gt;
        ///      &lt;string key=&quot;MMS_LOAD_CHAR_STATE&quot;&gt;Load Character State&lt;/string&gt;
        ///      &lt;string key=&quot;MMS_SAVE_CHAR_STATE&quot;&gt;Save Character State&lt;/string&gt;
        ///      &lt;string key=&quot;MMS_SAVE_CHAR_IMG&quot;&gt;Save Character Image&lt;/st [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EN_US_Locale {
            get {
                return ResourceManager.GetString("EN_US_Locale", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap file2_30 {
            get {
                object obj = ResourceManager.GetObject("file2_30", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap info_30 {
            get {
                object obj = ResourceManager.GetObject("info_30", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lock_closed_40 {
            get {
                object obj = ResourceManager.GetObject("lock_closed_40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap send_box2_40 {
            get {
                object obj = ResourceManager.GetObject("send_box2_40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Untitled1 {
            get {
                object obj = ResourceManager.GetObject("Untitled1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
